---
- hosts: all
  become: true
  vars:
      destination_application_path: /home/$USER
      source_code: ../source_code
      node_modules_dir_name: node_modules

  tasks:
      - name: Display paths of all files in dir
        ansible.builtin.debug: msg={{ lookup('ansible.builtin.fileglob', '../source_code') }}

      - name: Copy each file over that matches the given pattern
        ansible.builtin.copy:
            src: "{{ item }}"
            dest: "{{ destination_application_path }}"
            owner: "root"
            mode: 0600
        with_fileglob:
            - "{{ source_code }}/*"

      - name: Run a command
        ansible.builtin.shell: sudo apt install -y npm
        args:
            executable: /bin/bash

      # - name: Run a command
      #   ansible.builtin.shell: npm init
      #   args:
      #     executable: /bin/bash

      - name: Creates directory for node_modules
        file:
            path: "{{ node_modules_dir_name }}"
            state: directory

      - name: Install packages based on package.json.
        community.general.npm:
            path: "{{ node_modules_dir_name }}"

      - name: Creates directory for mongo db data
        file:
            path: /data/db
            state: directory

      - name: Run a command
        ansible.builtin.shell: docker run --name mongodb --rm -d -p 27017:27017 -v "{{ destination_application_path }}":/data/db mongo && node index.js
        args:
            executable: /bin/bash
